src/accounts/urls.py
from accounts.views import AccountLoginView, AccountLogoutView, AccountRegistrationView, AccountUpdateView, \
    ChangePasswordView

from django.urls import path

app_name = 'accounts'

urlpatterns = [

    path('registration', AccountRegistrationView.as_view(), name='registration'),
    path('login', AccountLoginView.as_view(), name='login'),
    path('logout', AccountLogoutView.as_view(), name='logout'),
    path('profile', AccountUpdateView.as_view(), name='profile'),
    path('password_change', ChangePasswordView.as_view(), name='password_change'),

]

src/lms/urls.py
from core.views import index

import debug_toolbar

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', index, name='index'),
    path('__debug__/', include(debug_toolbar.urls)),
    path('admin/', admin.site.urls),
    path('students/', include('students.urls')),
    path('teachers/', include('teacher.urls')),
    path('groups/', include('groups.urls')),
    path('classroom/', include('classrooms.urls')),
    path('accounts/', include('accounts.urls'))
]

urlpatterns += \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>LMS</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
</head>
<body>



<nav class="navbar navbar-default navbar-fixed-top navbar-expand-lg navbar-dark bg-primary font-weight-bold">

    <div class="container">

    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'index' %}">LMS</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">

            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'list_students' %}">Students</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'list_teachers' %}">Teachers</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'list_groups' %}">Groups</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'list_classroom' %}">Classrooms</a>
            </li>
            <li class="text-end">

            </li>
          </ul>
          <div class="text-light">
              {% if user.is_authenticated %}
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="media">
                <div class="img-circle.vert">
                    <img class="rounded-circle p-1 m-1" width="40" height="40"  src="{{ user.profile.image.url }}">
                </div>
              </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'accounts:profile' %}">
                        {{ user }}: Check profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'accounts:logout' %}">Log Out</a>
                </li>
              {% else %}
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'accounts:registration' %}">Sign Up</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'accounts:login' %}">Sign In</a>
                </li>
              </ul>
              {% endif %}
          </div>
        </div>
      </div>

    </div>

</nav>



<div class="container">

        {% include 'includes/messages.html' %}

        <div class="border rounded text-center p-3 m-3 bg-light text-dark">
            {% block header %}
                <h1> Welcome to LMS! </h1>
            {% endblock %}
        </div>

        {% block main %}
        {% endblock %}
</div>



</body>
</html>

src/templates/index.html
{% extends 'base.html' %}

{% block main %}

    <a href="{% url 'list_students'%}" style="font-size: 22px">Students</a>
    <br>
    <a href="{% url 'list_groups'%}" style="font-size: 22px">Groups</a>
    <br>
    <a href="{% url 'list_teachers'%}" style="font-size: 22px">Teachers</a>

{% endblock %}